### PR TITLE
fix column reviews_text in field list is ambiguous

### PR DESCRIPTION
**Pull request by ruden**

### CODE REVIEW

**Comment by BrockleyJohn** [comment]
How do I reproduce the error in an uncustomised store?

**Comment by ruden** [comment]
Install box reviews and add a review.

**Comment by BrockleyJohn** [comment]
[https://bromleybr.co.uk/phoenix/](https://bromleybr.co.uk/phoenix/)

**Comment by ruden** [comment]
http://demo.osclab.com/ce/

**Pull request closed without merging**
