### PR TITLE
Bootstrapped reviews, tax_classes, tax_rates

### PR DESCRIPTION
**Pull request by Denzel76**
**IMPORTANT: Please do not create a PR unless you have first created an ISSUE and your issue has been discussed and accepted.**

*Any change needs to be discussed BEFORE you make a Pull Request. Failure to do so WILL result in immediate rejection of your Pull Request.*

Please provide enough information in your raised ISSUE so that others can understand and review the details of your Test Plan:

Explain the **details** for making this change. What existing problem does the pull request solve?
Example: When "Adding a function to do X", explain why it is necessary to have a way to do X.

**Test plan (required)**

Demonstrate the code is solid.

Example: Link to an install that shows your new code in action.  If that is not possible provide screenshots and/or the exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### CODE REVIEW

**Comment by gburton** [comment]
Ah, thank Denzel.  In between you doing your work on these pages and now, changes were made which has led to conflicts.  If you have time can you revisit the pages and solve the conflicts?

**Comment by Denzel76** [comment]
I'll try look at it till tomorrow...

Am 16. März 2020 18:56:34 MEZ schrieb gburton <notifications@github.com>:

**Comment by ecartz** [comment]
I sometimes find it easier to do this in something like GitHub Desktop (or just plain git on Linux) by cutting a new branch, syncing to the current development branch (1.0.5.5 now), and copying the modified files into it and looking at what changes that makes.  Then, which of them are you making intentionally and which are accidental reversions.  Remove the accidental reversions and commit the new versions of the files.  

```
git clone https://github.com/Denzel76/CE-Phoenix.git 1.0.5.5
cd 1.0.5.5
git remote add upstream https://github.com/gburton/CE-Phoenix.git
git fetch upstream
git checkout -t upstream/1.0.5.5
```

That's the command line commands to run (in Linux or Git Bash on Windows) to cut a new branch synchronized to the current development branch.  Note that the first two 1.0.5.5 could be named something else.  They need to be the same as each other, but they don't need to be 1.0.5.5.  The third has to be the current development branch.  

To see what changed in those files since you cut your original branch:  

```
git diff d37dd01ee6548570d5d9b154d28f5421c14ea2d2 HEAD admin/reviews.php admin/tax_rates.php admin/tax_classes.php admin/includes/languages/english/reviews.php
```

If you run that before you make any changes, that will show you what changed in Gary's branch.  

```
git diff d37dd01ee6548570d5d9b154d28f5421c14ea2d2 ebd21482e246c760331d8d1edaab1a6cb88bc537 admin/reviews.php admin/tax_rates.php admin/tax_classes.php admin/includes/languages/english/reviews.php
```

That command does the exact same thing right now, but it will still show the same thing after you start making changes.  

You can also do a git merge or git pull in your current master branch.  But I find that it does the diff from the wrong side.  So I find it easier to copy the files to a new branch, possibly after already doing the git pull (may require adding a new remote).  

After you've committed all your changes and have everything the way that you want it, you can, from inside that directory, do 

```
git push origin 1.0.5.5:1.0.5.5
```

Then sign in and it will push your changes to your fork.  You can then do a new pull request from your fork to Gary's.  

I used https URLs, but the same process would work with ssh URLs if you already have the SSH keys set up.

**Comment by gburton** [comment]
Aim for 1.0.5.6

**Pull request closed without merging**
