### PR TITLE
sort hook files before loading

### PR DESCRIPTION
**Pull request by BrockleyJohn**
**Test plan **

Ask 14steve14 and peterpil19 to validate that fix works (both have hit this issue on their platform)

### CODE REVIEW

**Comment by gburton** [comment]
`function call($group, $action, $arr = array()) {
      $result = '';
      
      @ksort($this->_hooks[$this->_site][$group][$action]); // new sorting

      foreach ( @(array)$this->_hooks[$this->_site][$group][$action] as $hook ) {`

**Comment by BrockleyJohn** [comment]
The array's already in (numeric) key order:
Array
                (
                    [0] => fontAwesome
                    [1] => styleSheets
                    [2] => bootStrap
                )

**Comment by BrockleyJohn** [comment]
asort pushed instead

**Comment by gburton** [comment]
I've tested your solution.  It seems to work well, and looks more flexible than the 1 liner.

**Comment by BrockleyJohn** [comment]
both work for me! shall I back out the last commit?

**Comment by gburton** [comment]
All good, thank you.  I'll cherry pick your first one into 1.0.2.5
Thanks!

**Comment by peterpil19** [comment]
Hi,
I confirm this solution works on my test shop.
Peter

**Comment by BrockleyJohn** [comment]
@peterpil19 thanks

**Comment by gburton** [comment]
TY guys.  I'll drop this into 1.0.2.5.

**Pull request closed without merging**
