### PR TITLE
Db varchar modify - rewritten 240120

### PR DESCRIPTION
**Pull request by mfleeson**
**IMPORTANT: Please do not create a PR unless you have first created an ISSUE and your issue has been discussed and accepted.**

*Any change needs to be discussed BEFORE you make a Pull Request. Failure to do so WILL result in immediate rejection of your Pull Request.*

Please provide enough information in your raised ISSUE so that others can understand and review the details of your Test Plan:

Explain the **details** for making this change. What existing problem does the pull request solve?
Example: When "Adding a function to do X", explain why it is necessary to have a way to do X.

**Test plan (required)**
Ran through sql tool, all queries work as before with select fields enlarged to 255 characters.

Demonstrate the code is solid.

Example: Link to an install that shows your new code in action.  If that is not possible provide screenshots and/or the exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### CODE REVIEW

**Comment by mfleeson** [comment]
I am beginning to really hate git software. I followed Matt's instructions, only changed one file and the pull request has dragged in all of the other changes!

**Comment by gburton** [comment]
TY.  No worries, I'll cherry pick the SQL change.  Will leave this open & pending until I can get onto the other computer to do that.

**Comment by mfleeson** [comment]
[DB_Update_VarChar.sql.txt](https://github.com/gburton/CE-Phoenix/files/4108758/DB_Update_VarChar.sql.txt)

Here's just the update statements.

**Comment by gburton** [comment]
Cherry-Picked to 1.0.4.4

TY

**Comment by ecartz** [comment]
Just as an FYI, the reason why it pulled in the extra changes was that you did the PR against master rather than 1.0.4.4 this time.  So it was attempting to merge the current 1.0.4.4 plus your change into master.  

No additional work needed.  I just wanted to explain what happened for future PRs.

**Pull request closed without merging**
