### PR TITLE
Application top hook call 

### PR DESCRIPTION
**Pull request by raiwa**
**IMPORTANT: Please do not create a PR unless you have first created an ISSUE and your issue has been discussed and accepted.**

*Any change needs to be discussed BEFORE you make a Pull Request. Failure to do so WILL result in immediate rejection of your Pull Request.*

Please provide enough information in your raised ISSUE so that others can understand and review the details of your Test Plan:

Explain the **details** for making this change. What existing problem does the pull request solve?
Example: When "Adding a function to do X", explain why it is necessary to have a way to do X.

**Test plan (required)**

Demonstrate the code is solid.

Example: Link to an install that shows your new code in action.  If that is not possible provide screenshots and/or the exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### CODE REVIEW

**Comment by gburton** [comment]
I assume it's just 039b26c ?

**Comment by raiwa** [comment]
Yes

**Comment by gburton** [comment]
1.0.2.3

**Comment by gburton** [comment]
TY

**Pull request closed without merging**
